version: '3.8'
services:
  web:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: complearn_web
    restart: unless-stopped
    ports:
      - "3000:80"  # Map container's port 80 to host's port 3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
