version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: complearn_redis
    command: redis-server --requirepass "${VITE_REDIS_PASSWORD:-complearn}" --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${VITE_REDIS_PASSWORD:-complearn}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    profiles:
      - redis

  qsearch:
    build:
      context: .
      target: cpp-builder
    container_name: complearn_cpp
    networks:
      - app_network
    command: ./runtests --unit
    profiles:
      - app
    depends_on:
      redis:
        condition: service_healthy

  ncd-calculator:
    build:
      context: ./ncd-calculator
      args:
        - VITE_API_URL=${VITE_API_URL:-http://complearn-genbank:3001}
    container_name: complearn_web
    restart: unless-stopped
    env_file:
      - ./ncd-calculator/.env.production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    networks:
      - app_network
    profiles:
      - app
    volumes:
      - /home/nginx/hosts:/home/nginx/hosts
    depends_on:
      redis:
        condition: service_healthy
      complearn-genbank:
        condition: service_started

  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    env_file:
      - ./complearn-genbank/.env.production
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  complearn-genbank:
    build:
      context: ./complearn-genbank
    container_name: complearn_api
    restart: unless-stopped
    volumes:
      - complearn_logs:/var/log/complearn_api
    env_file:
      - ./complearn-genbank/.env.production
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_URL=redis://complearn_redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-complearn}
    ports:
      - "3001:3001"
    networks:
      - app_network
    profiles:
      - app
    depends_on:
      mysql_container:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local
  complearn_logs:
    driver: local

networks:
  app_network:
    driver: bridge