version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: complearn_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - redis

  qsearch:
    build:
      context: .
      target: cpp-builder
    container_name: complearn_cpp
    networks:
      - app_network
    command: ./runtests --unit
    profiles:
      - app
    depends_on:
      redis:
        condition: service_healthy

  ncd-calculator:
    build:
      context: ./ncd-calculator
      args:
        - VITE_API_URL=${VITE_API_URL:-http://complearn-genbank:3001}
    container_name: complearn_web
    restart: unless-stopped
    env_file:
      - ./ncd-calculator/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    networks:
      - app_network
    profiles:
      - app
    depends_on:
      redis:
        condition: service_healthy
      complearn-genbank:
        condition: service_started

  complearn-genbank:
    build:
      context: ./complearn-genbank
    container_name: complearn_api
    restart: unless-stopped
    volumes:
      - /var/log/complearn_api:/var/log/complearn_api
    env_file:
      - ./complearn-genbank/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - app_network
    profiles:
      - app
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /cache/redis

networks:
  app_network:
    driver: bridge